Repository Dialosoft/frontend, pull requests merged in 2024-08, with the labels that each got.

#16 chore: upgrade package.json
  main/package.json
Labels: documentation

#23 Feat/members
  main/src/components/User/rol.tsx
  main/src/components/side_info/members/main.tsx
  main/src/components/side_info/members/member.tsx
Labels: enhancement

#22 Develop
  .gitignore
  .vscode/settings.json
  Dockerfile
  Dockerfile.nginx
  dashboard/.eslintrc.json
  dashboard/next.config.mjs
  dashboard/package.json
  dashboard/postcss.config.mjs
  dashboard/src/app/globals.css
  dashboard/src/app/layout.tsx
  dashboard/src/app/page.tsx
  dashboard/tailwind.config.ts
  dashboard/tsconfig.json
  docker-compose.yml
  main/.env
  main/.eslintrc.json
  main/next.config.mjs
  main/package.json
  main/postcss.config.mjs
  main/src/app/(forum)/layout.tsx
  main/src/app/(forum)/page.tsx
  main/src/app/(session)/layout.tsx
  main/src/app/(session)/login/page.tsx
  main/src/app/(session)/register/page.tsx
  main/src/app/globals.css
  main/src/components/Post/interactions.tsx
  main/src/components/Post/overview.tsx
  main/src/components/Post/tags.tsx
  main/src/components/Post/voting_chip.tsx
  main/src/components/Session/Login/form.tsx
  main/src/components/Session/Register/form.tsx
  main/src/components/User/chip.tsx
  main/src/components/User/rol.tsx
  main/src/components/header/dark_tester.tsx
  main/src/components/header/main.tsx
  main/src/components/header/search.tsx
  main/src/components/header/skeletons.tsx
  main/src/components/main_section/category.tsx
  main/src/components/main_section/last_post.tsx
  main/src/components/main_section/main.tsx
  main/src/components/side_info/last_articles/article.tsx
  main/src/components/side_info/last_articles/main.tsx
  main/src/components/side_info/members/main.tsx
  main/src/components/side_info/members/member.tsx
  main/src/middleware.ts
  main/src/schemas/Session/login.ts
  main/src/schemas/Session/register.ts
  main/src/utils/getWidth.ts
  main/tailwind.config.ts
  main/tsconfig.json
  nginx/default.conf
Labels: enhancement

#34 Feat/lint
  main/.eslintrc.json
  main/package.json
Labels: enhancement

#35 feat: add pull-request-lint.yml
  .github/workflows/pull-request-lint.yml
  .gitignore
  .prettierrc
  dashboard/package-lock.json
  main/package-lock.json
  main/package.json
Labels: enhancement

#40 Fix/pull request
  .github/workflows/pull-request-lint.yml
Labels: bug

#39 chore(dependabot): change update frequency to daily
  .github/dependabot.yml
Labels: dependencies

#42 Style/header
  main/src/app/(forum)/(account)/a/profile/page.tsx
  main/src/app/(forum)/page.tsx
  main/src/components/header/main.tsx
  main/src/components/header/notifications.tsx
  main/src/components/header/options.tsx
  main/tailwind.config.ts
Labels: Code Style

#43 Style/login
  main/src/app/(session)/login/page.tsx
  main/src/app/(session)/register/page.tsx
  main/src/components/Session/Login/form.tsx
  main/src/components/Session/Register/form.tsx
  main/src/schemas/Session/login.ts
  main/src/schemas/Session/register.ts
Labels: enhancement, Code Style, Refactor

#44 Chore/dependabot
  .github/dependabot.yml
Labels: enhancement

#57 Chore/docker
  Dockerfile
  Dockerfile.dev
  main/package-lock.json
Labels: enhancement, dependencies

#58 Feat/login
  main/src/components/Session/Login/form.tsx
  main/src/utils/Session/login.ts
  main/src/utils/Session/register.ts
Labels: enhancement

#59 fix: resolve lint and Prettier issues in GitHub Actions
  .github/workflows/pull-request-lint.yml
Labels: bug

#61 fix: resolve GitHub Actions issues with tj-actions/changed-files
  .github/workflows/pull-request-lint.yml
Labels: bug

#65 Feat/visible password
  main/src/components/Session/Login/form.tsx
  main/src/components/Session/Register/form.tsx
Labels: enhancement

#67 Fix/schemas
  main/src/components/Session/Register/form.tsx
  main/src/utils/Session/login.ts
  main/src/utils/Session/register.ts
Labels: bug

#60 feat: add redirect in middleware for login/register if refresh token …
  main/src/middleware.ts
  main/src/schemas/Session/login.ts
  main/src/schemas/Session/register.ts
  main/src/utils/Session/login.ts
  main/src/utils/Session/refreshToken.ts
Labels: enhancement

#69 fix: resolve redirect loop issue
  main/src/middleware.ts
  main/src/utils/Session/refreshToken.ts
Labels: bug

#92 Fix/lint
  .prettierrc
  main/.eslintrc.json
  main/.prettierrc
  main/package.json
  main/src/app/(forum)/(account)/a/profile/page.tsx
  main/src/app/(forum)/(account)/a/saved/page.tsx
  main/src/app/(forum)/(account)/a/settings/account/change_password/page.tsx
  main/src/app/(forum)/(account)/a/settings/account/page.tsx
  main/src/app/(forum)/(account)/a/settings/page.tsx
  main/src/app/(forum)/(categories)/c/[categoryID]/[...post]/page.tsx
  main/src/app/(forum)/(categories)/c/[categoryID]/create/page.tsx
  main/src/app/(forum)/(categories)/c/[categoryID]/page.tsx
  main/src/app/(forum)/layout.tsx
  main/src/app/(session)/login/page.tsx
  main/src/app/(session)/register/page.tsx
  main/src/app/(session)/reset-password/page.tsx
  main/src/app/(session)/reset-password/token/page.tsx
  main/src/components/Forum/Account/Profile_Section/profile.tsx
  main/src/components/Forum/Account/Profile_Section/user_posts.tsx
  main/src/components/Forum/Account/Saved_Section/SvdComment.tsx
  main/src/components/Forum/Account/Saved_Section/SvfPost.tsx
  main/src/components/Forum/Account/Settings_Section/settingsnav.tsx
  main/src/components/Forum/Account/movilenav.tsx
  main/src/components/Forum/Account/sidenav.tsx
  main/src/components/Forum/Header/Notify/template.tsx
  main/src/components/Forum/Header/Options/notify.tsx
  main/src/components/Forum/Header/User/UserChip.tsx
  main/src/components/Forum/Header/User/chip.tsx
  main/src/components/Forum/Header/User/main.tsx
  main/src/components/Forum/Header/main.tsx
  main/src/components/Forum/Header/menu.tsx
  main/src/components/Forum/Messages/MessageInbox/chat_preview.tsx
  main/src/components/Forum/Messages/chat_view.tsx
  main/src/components/Forum/Post/interactions.tsx
  main/src/components/Forum/Post/overview.tsx
  main/src/components/Forum/Post/voting_chip.tsx
  main/src/components/Forum/Post_Section/comments.tsx
  main/src/components/Forum/Post_Section/post.tsx
  main/src/components/Forum/main_section/addForum.tsx
  main/src/components/Forum/main_section/main.tsx
  main/src/components/Post_Section/create/text_editor.tsx
  main/src/components/Session/Login/form.tsx
  main/src/components/Session/Register/form.tsx
  main/src/components/Session/Reset-Password/form.tsx
  main/src/components/Session/Reset-Password/token.tsx
  main/src/schemas/Session/changePass.ts
  main/src/schemas/Session/register.ts
  main/src/schemas/Session/resetPassword.ts
Labels: bug

#94 Feat/profile
  main/src/app/(forum)/(account)/a/settings/account/change_password/page.tsx
  main/src/app/(forum)/(account)/a/settings/account/page.tsx
  main/src/components/Forum/Account/movilenav.tsx
  main/src/components/Forum/Header/Options/user.tsx
  main/src/components/Forum/Header/menu.tsx
  main/src/middleware.ts
Labels: bug, enhancement
